using Comments.Application.Abstractions;
using Comments.Application.Abstractions.Persistence;
using Comments.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Npgsql;
using NpgsqlTypes;
using System.Diagnostics;
using System.Globalization;

namespace Comments.Infrastructure.Persistence;

/// <summary>
/// Idempotent, multi-instance-safe migration bootstrap (docs/API-v2.md §8.4): applies pending EF
/// migrations while holding a PostgreSQL session advisory lock, so N API instances starting at
/// once serialise instead of racing.
/// </summary>
public static class MigrationRunner
{
    // Arbitrary but stable application-wide lock key (comments-api migrations).
    private const long AdvisoryLockKey = 727084321;

    public static async Task ApplyMigrationsAsync(this IServiceProvider services, CancellationToken cancellationToken = default)
    {
        using var scope = services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var logger = scope.ServiceProvider.GetService<ILogger<AppDbContext>>();

        var connectionString = db.Database.GetConnectionString()
                               ?? throw new InvalidOperationException("ConnectionStrings:Default is not configured.");

        await using var lockConnection = new NpgsqlConnection(connectionString);
        try
        {
            await lockConnection.OpenAsync(cancellationToken);
        }
        catch (PostgresException ex) when (ex.SqlState == PostgresErrorCodes.InvalidCatalogName)
        {
            // Fresh host/CI database: create it once before taking the advisory lock (compose and
            // the test harness normally pre-create it; this keeps local/`run-dev` starts working).
            await EnsureDatabaseExistsAsync(connectionString, cancellationToken);
            await lockConnection.OpenAsync(cancellationToken);
        }

        await using (var acquire = lockConnection.CreateCommand())
        {
            acquire.CommandText = "SELECT pg_advisory_lock($1)";
            acquire.Parameters.Add(new NpgsqlParameter { Value = AdvisoryLockKey });
            await acquire.ExecuteNonQueryAsync(cancellationToken);
        }

        try
        {
            logger?.LogInformation("Applying database migrations (advisory lock held)...");
            await db.Database.MigrateAsync(cancellationToken);
            logger?.LogInformation("Database migrations are up to date.");
        }
        finally
        {
            await using var release = lockConnection.CreateCommand();
            release.CommandText = "SELECT pg_advisory_unlock($1)";
            release.Parameters.Add(new NpgsqlParameter { Value = AdvisoryLockKey });
            await release.ExecuteNonQueryAsync(cancellationToken);
        }
    }

    private static async Task EnsureDatabaseExistsAsync(string connectionString, CancellationToken cancellationToken)
    {
        var builder = new NpgsqlConnectionStringBuilder(connectionString);
        var database = builder.Database;
        if (string.IsNullOrWhiteSpace(database) || string.Equals(database, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        builder.Database = "postgres";
        await using var admin = new NpgsqlConnection(builder.ConnectionString);
        await admin.OpenAsync(cancellationToken);

        await using var create = admin.CreateCommand();
        create.CommandText = $"CREATE DATABASE \"{database.Replace("\"", "\"\"")}\"";
        try
        {
            await create.ExecuteNonQueryAsync(cancellationToken);
        }
        catch (PostgresException ex) when (ex.SqlState == PostgresErrorCodes.DuplicateDatabase)
        {
            // Another instance created it first — fine.
        }
    }
}

/// <summary>Design-time factory so <c>dotnet ef migrations</c> works without the API project.</summary>
public sealed class AppDbContextFactory : Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory<AppDbContext>
{
    public AppDbContext CreateDbContext(string[] args)
    {
        var connectionString = Environment.GetEnvironmentVariable("ConnectionStrings__Default")
            ?? Environment.GetEnvironmentVariable("ConnectionStrings:Default")
            ?? "Host=localhost;Port=55432;Database=comments;Username=comments;Password=comments";

        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseNpgsql(connectionString)
            .Options;

        return new AppDbContext(options);
    }
}

/// <summary>
/// Batched bulk generator for <c>POST /api/dev/seed</c> (docs/API-v2.md §3.4). Uses binary COPY
/// with explicit ids (the identity is GENERATED BY DEFAULT, so explicit values are accepted) and
/// then advances the identity sequence.
/// </summary>
public sealed class CommentSeeder : ICommentSeeder
{
    private const string CopySql =
        "COPY comments (id, parent_id, user_name, email, home_page, text_html, text_plain, created_at, client_ip, user_agent) " +
        "FROM STDIN (FORMAT BINARY)";

    private readonly AppDbContext _db;
    private readonly IClock _clock;
    private readonly ILogger<CommentSeeder> _logger;

    public CommentSeeder(AppDbContext db, IClock clock, ILogger<CommentSeeder> logger)
    {
        _db = db;
        _clock = clock;
        _logger = logger;
    }

    public async Task<SeedOutcome> SeedAsync(SeedOptions options, CancellationToken cancellationToken = default)
    {
        var watch = Stopwatch.StartNew();

        var total = Math.Max(0, options.Count);
        var roots = Math.Clamp(options.Roots <= 0 ? Math.Max(1, total / 10) : options.Roots, 0, Math.Max(1, total));
        var depth = Math.Clamp(options.Depth <= 0 ? 1 : options.Depth, 1, 32);
        var chunkSize = Math.Clamp(options.BatchSize <= 0 ? 25_000 : options.BatchSize, 5_000, 100_000);

        // Dedicated connection with a long command timeout: a 1M-row seed takes minutes, and the
        // default 30 s aborts the COPY while the server-side command keeps running (QA/perf).
        var connectionString = _db.Database.GetConnectionString()
            ?? throw new InvalidOperationException("ConnectionStrings:Default is not configured.");
        var connectionBuilder = new NpgsqlConnectionStringBuilder(connectionString) { CommandTimeout = 900 };

        await using var connection = new NpgsqlConnection(connectionBuilder.ConnectionString);
        await connection.OpenAsync(cancellationToken);

        // Bulk dev seeding does not need synchronous WAL durability; this is the single biggest
        // throughput win and keeps the client/server in sync per chunk.
        await ExecuteAsync(connection, null, "SET synchronous_commit = off", cancellationToken);

        // ---- Phase 1: reserve the whole id range under a short EXCLUSIVE lock (QA-301). ----
        long baseId;
        await using (var reservation = await connection.BeginTransactionAsync(cancellationToken))
        {
            if (options.Clear)
            {
                await ExecuteAsync(connection, reservation, "TRUNCATE comments, attachments RESTART IDENTITY CASCADE", cancellationToken);
            }

            // Blocks concurrent INSERT (ROW EXCLUSIVE) only for the reservation, not the COPY.
            await ExecuteAsync(connection, reservation, "LOCK TABLE comments IN EXCLUSIVE MODE", cancellationToken);
            baseId = await ScalarLongAsync(connection, reservation, "SELECT COALESCE(MAX(id), 0) FROM comments", cancellationToken);

            var reserved = baseId + (long)total;
            await ExecuteAsync(
                connection,
                reservation,
                $"SELECT setval(pg_get_serial_sequence('comments','id'), {reserved}, true)",
                cancellationToken);

            await reservation.CommitAsync(cancellationToken);
        }

        // Parents are precomputed so the COPY loop only streams rows.
        var parents = BuildParents(total, roots, depth);
        var now = _clock.UtcNow;

        long created = 0;
        for (var start = 0; start < total; start += chunkSize)
        {
            var end = Math.Min(start + chunkSize, total);

            await using var chunk = await connection.BeginTransactionAsync(cancellationToken);
            await using (var writer = await connection.BeginBinaryImportAsync(CopySql, cancellationToken))
            {
                for (var i = start; i < end; i++)
                {
                    var id = baseId + i + 1;
                    var parentIndex = parents[i];

                    await writer.StartRowAsync(cancellationToken);
                    await writer.WriteAsync(id, NpgsqlDbType.Bigint, cancellationToken);
                    if (parentIndex < 0)
                    {
                        await writer.WriteNullAsync(cancellationToken);
                    }
                    else
                    {
                        await writer.WriteAsync(baseId + parentIndex + 1, NpgsqlDbType.Bigint, cancellationToken);
                    }

                    await writer.WriteAsync($"User{id % 100000:D5}", NpgsqlDbType.Varchar, cancellationToken);
                    await writer.WriteAsync($"user{id % 100000:D5}@example.com", NpgsqlDbType.Varchar, cancellationToken);
                    await writer.WriteNullAsync(cancellationToken); // home_page
                    await writer.WriteAsync($"<i>Seed comment {id}</i>", NpgsqlDbType.Text, cancellationToken);
                    await writer.WriteAsync($"Seed comment {id}", NpgsqlDbType.Text, cancellationToken);
                    await writer.WriteAsync(now.AddMilliseconds(-(i % 86_400_000)), NpgsqlDbType.TimestampTz, cancellationToken);
                    await writer.WriteNullAsync(cancellationToken); // client_ip
                    await writer.WriteNullAsync(cancellationToken); // user_agent
                    created++;
                }

                await writer.CompleteAsync(cancellationToken);
            }

            await chunk.CommitAsync(cancellationToken);
            _logger.LogInformation("Seeded {Created}/{Total} comments", created, total);
        }

        _logger.LogInformation(
            "Seeded {Created} comments ({Roots} roots, depth {Depth}) in {ElapsedMs} ms",
            created,
            roots,
            depth,
            watch.ElapsedMilliseconds);

        return new SeedOutcome(created, roots, watch.ElapsedMilliseconds);
    }

    /// <summary>
    /// Builds the parent index for every generated comment deterministically: the first
    /// <paramref name="roots"/> rows are roots, the rest attach to an earlier row while staying
    /// within <paramref name="depth"/>.
    /// </summary>
    private static int[] BuildParents(int total, int roots, int depth)
    {
        var parents = new int[total];
        var depths = new int[total];
        var random = new Random(20261004);

        for (var i = 0; i < total; i++)
        {
            if (i < roots)
            {
                parents[i] = -1;
                depths[i] = 0;
                continue;
            }

            var candidate = random.Next(i);
            var guard = 0;
            while (depths[candidate] >= depth && guard++ < 64)
            {
                candidate = random.Next(i);
            }

            parents[i] = candidate;
            depths[i] = depths[candidate] + 1;
        }

        return parents;
    }

    private static async Task ExecuteAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction? transaction,
        string sql,
        CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        command.Transaction = transaction;
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    private static async Task<long> ScalarLongAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction? transaction,
        string sql,
        CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        command.Transaction = transaction;
        var value = await command.ExecuteScalarAsync(cancellationToken);
        return value is null or DBNull ? 0L : Convert.ToInt64(value, CultureInfo.InvariantCulture);
    }
}
