using System.ComponentModel.DataAnnotations;

namespace Comments.Domain;

/// <summary>
/// A user comment. Root comments have <see cref="ParentId"/> == null, answers point to their parent.
/// </summary>
public class Comment
{
    /// <summary>
    /// Surrogate key. Mapped to PostgreSQL <c>bigint GENERATED BY DEFAULT AS IDENTITY</c>; the
    /// CLR type stays <see cref="int"/> to preserve the v1 public surface (docs/API-v2.md §0.1).
    /// </summary>
    public int Id { get; set; }

    /// <summary>Self-reference to the parent comment; null for a root comment.</summary>
    public int? ParentId { get; set; }

    public Comment? Parent { get; set; }

    public ICollection<Comment> Replies { get; set; } = new List<Comment>();

    [MaxLength(50)]
    public string UserName { get; set; } = string.Empty;

    [MaxLength(100)]
    public string Email { get; set; } = string.Empty;

    [MaxLength(200)]
    public string? HomePage { get; set; }

    /// <summary>Sanitised HTML (allowlist: a[href,title], code, i, strong).</summary>
    public string TextHtml { get; set; } = string.Empty;

    /// <summary>Same text without any markup.</summary>
    public string TextPlain { get; set; } = string.Empty;

    /// <summary>
    /// Snapshot of the parent's flat text captured when this reply was created
    /// (docs/DESIGN-v2.1-decisions.md §1). Null for root comments, for legacy rows and when the
    /// parent had no text. Plain text only — never HTML.
    /// </summary>
    public string? QuotedText { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Client IPv4/IPv6 of the first trusted hop (docs/API-v2.md §6).</summary>
    [MaxLength(64)]
    public string? ClientIp { get; set; }

    [MaxLength(512)]
    public string? UserAgent { get; set; }

    public int? AttachmentId { get; set; }

    public Attachment? Attachment { get; set; }
}
