-- =============================================================================
-- SPA «Комментарии» — PostgreSQL schema (v2, stage Middle+)
--
-- This file is a human-readable, idempotent DDL equivalent of the EF Core model
-- and migrations located in:
--   src/Backend/Comments.Infrastructure/Persistence/Migrations/
--
-- The application applies its own EF Core migrations at startup; this script is
-- provided for review (compare design vs. implementation) and for manual
-- bootstrap. It is safe to run repeatedly.
--
-- MySQL-dialect schema of the previous stage is kept separately in db/schema.sql.
-- =============================================================================

-- ------------------------------------------------------------------ comments
CREATE TABLE IF NOT EXISTS comments (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id      bigint       NULL,
    user_name      varchar(50)  NOT NULL,
    email          varchar(100) NOT NULL,
    home_page      varchar(200) NULL,
    text_html      text         NOT NULL,   -- already sanitised (allow-list)
    text_plain     text         NOT NULL,   -- same text without markup
    created_at     timestamptz  NOT NULL DEFAULT now(),
    client_ip      varchar(64)  NULL,       -- first trusted hop (X-Forwarded-For)
    user_agent     varchar(512) NULL,
    attachment_id  bigint       NULL,
    CONSTRAINT fk_comments_parent
        FOREIGN KEY (parent_id) REFERENCES comments (id) ON DELETE RESTRICT
);

-- ----------------------------------------------------------------- attachments
CREATE TABLE IF NOT EXISTS attachments (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name       varchar(260) NOT NULL,
    stored_name     varchar(260) NOT NULL,
    storage_path    varchar(512) NOT NULL,
    content_type    varchar(100) NOT NULL,
    kind            varchar(10)  NOT NULL,  -- 'image' | 'text'
    size_bytes      bigint       NOT NULL,
    width           integer      NULL,
    height          integer      NULL,
    original_width  integer      NULL,
    original_height integer      NULL,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    sha256          varchar(64)  NOT NULL
);

-- comments.attachment_id -> attachments.id (added after attachments exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_comments_attachment'
    ) THEN
        ALTER TABLE comments
            ADD CONSTRAINT fk_comments_attachment
            FOREIGN KEY (attachment_id) REFERENCES attachments (id) ON DELETE SET NULL;
    END IF;
END $$;

-- --------------------------------------------------------------------- indexes
-- Reply lookup (cascade tree, BFS one query per level).
CREATE INDEX IF NOT EXISTS ix_comments_parent_id
    ON comments (parent_id);

-- LIFO default + keyset pagination on created_at.
CREATE INDEX IF NOT EXISTS ix_comments_created_at_id
    ON comments (created_at DESC, id DESC);

-- Tree assembly: children of a known parent, ordered by creation.
CREATE INDEX IF NOT EXISTS ix_comments_parent_created
    ON comments (parent_id, created_at, id);

-- Case-insensitive sorting by User Name / E-mail (used instead of SQLite NOCASE).
CREATE INDEX IF NOT EXISTS ix_comments_user_name_lower
    ON comments (lower(user_name));

CREATE INDEX IF NOT EXISTS ix_comments_email_lower
    ON comments (lower(email));

CREATE INDEX IF NOT EXISTS ix_attachments_kind
    ON attachments (kind);

CREATE INDEX IF NOT EXISTS ix_attachments_sha256
    ON attachments (sha256);

-- ---------------------------------------------------------------- notes
-- * Money/ids: bigint identity mirrors the JSON `id` (number) exposed by the API.
-- * text_html/text_plain are stored post-sanitisation: the write path validates
--   the allow-list (a[href,title], code, i, strong) and XHTML tag closure.
-- * client_ip/user_agent are required by the assignment (client identification).
-- * No plaintext secrets live in the database schema or the repository.
